### ISSUE TITLE
Install successful, but error on build

### ISSUE THREAD

**Issue by sriv** [GitbookIO/plugin-codetabs#1]
Gitbook version: 2.6.7 (Gitbook-cli: 2.1.3)

My book.json plugins section looks like this:

```
    "plugins": [
        "anchors@0.6.0",
        "ga@1.0.1",
        "codetabs@1.0.0"
    ],

```

`gitbook install` gives me this:

```
info: 3 plugins to install
info: install plugin anchors from npm (gitbook-plugin-anchors) with version 0.6.0
info: >> plugin anchors installed with success
info: install plugin ga from npm (gitbook-plugin-ga) with version 1.0.1
info: >> plugin ga installed with success
info: install plugin codetabs from npm (gitbook-plugin-codetabs) with version 1.0.0
info: >> plugin codetabs installed with success

Done, without error
```

`gitbook -d serve` throws this:

```
Error: Error loading plugins: gitbook-plugin-codetabs. Run 'gitbook install' to install plugins from NPM.
    at /Users/steam/.gitbook/versions/2.6.7/lib/book.js:349:62
    at _fulfilled (/Users/steam/.gitbook/versions/2.6.7/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/steam/.gitbook/versions/2.6.7/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/steam/.gitbook/versions/2.6.7/node_modules/q/q.js:749:13)
    at /Users/steam/.gitbook/versions/2.6.7/node_modules/q/q.js:557:44
    at flush (/Users/steam/.gitbook/versions/2.6.7/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sriv** [comment]
Checked this on an example at gitbook.com/sriv/test. Build fails with below log:

```
Downloading source
Extracting source
GitBook version is 2.6.7 
Tweaking book.json
Installing plugins
info: 3 plugins to install 
info: install plugin codetabs from npm (gitbook-plugin-codetabs) with version 1.0.0 
gitbook-plugin-codetabs@1.0.0 node_modules/gitbook-plugin-codetabs
└── escape-html@1.0.3
info: >> plugin codetabs installed with success 
info: No version specified, resolve plugin comment 
info: install plugin comment from npm (gitbook-plugin-comment) with version 0.2.1 
gitbook-plugin-comment@0.2.1 node_modules/gitbook-plugin-comment
info: >> plugin comment installed with success 
info: No version specified, resolve plugin autocover 
info: install plugin autocover from npm (gitbook-plugin-autocover) with version 1.2.1 
info: >> plugin autocover installed with success 

Done, without error
Building Site, will upload
info: loading book configuration....OK 
info: load plugin gitbook-plugin-codetabs ....ERROR
info: load plugin gitbook-plugin-comment ....OK 
info: load plugin gitbook-plugin-autocover ....OK 
info: load plugin gitbook-plugin-highlight ....OK 
info: load plugin gitbook-plugin-search ....OK 
info: load plugin gitbook-plugin-sharing ....OK 
info: load plugin gitbook-plugin-fontsettings ....OK 

Error: Error loading plugins: gitbook-plugin-codetabs. Run 'gitbook install' to install plugins from NPM.
```

**Comment by sriv** [comment]
Works with 3.0.0.pre-15. I guess the plugin has a pre-requisite of gitbook >-3.0.0.
